apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app
  name: app2
spec:
  containers:
  # - image: nginx:alpine
  #   name: app
  # - image: busybox
  #   name: subapp
  #   args:
  #     - sleep
  #     - infinity
  - image: hashicorp/http-echo
    name: echo
    args:
      - text="hello world"
      - listen=:8080
